Wireguard status handling
robbrockbank/felix pull request #2
Opened 2020-04-14 20:39 UTC by realgaurav

## Description

Wireguard status handling.

### Testing

`make build` works

2020-04-14 20:49 UTC, robbrockbank commented on daemon/daemon.go
> +			fc.handleWireguardStatusUpdate(ctx, msg)
You need to handle retries when the writing the status update fails.

Note that a perfectly valid failure scenario would be an update conflict where another user is updating the node resource at the same time.  Just nothing that here when you consider logging.

Also, because you may need to retry, this write processing should probably happen on a different go-routine similar to how the status updates are handled.

2020-04-14 21:43 UTC, realgaurav commented on daemon/daemon.go
> +			fc.handleWireguardStatusUpdate(ctx, msg)
Help me understand this comment better:
> Note that a perfectly valid failure scenario would be an update conflict where another user is updating the node resource at the same time. Just nothing that here when you consider logging.

Public-key in node resource is part of Node Status. In the scenario above, an admin is updating Node Status (or the public-key annotation)?

>...write processing should probably happen on a different go-routine...

`fc.readMessagesFromDataplane` is a separate go-routine currently. Is the intent here to unblock `fc.readMessagesFromDataplane` for other Workload/Host status updates?

2020-04-14 21:45 UTC, robbrockbank commented on daemon/daemon.go
> +			fc.handleWireguardStatusUpdate(ctx, msg)
Node and Node status are really the same resource.  K8s does some jiggery to make it appear (sometimes) like they are different but they aren't.  Therefore an update to the Node resource will affect the current revision of the Node status.

2020-04-14 21:54 UTC, robbrockbank commented on daemon/daemon.go
> +			fc.handleWireguardStatusUpdate(ctx, msg)
Yes - to ensure we don't block readMessagesFromDataplane. We want to retry the write until we either succeed, or until we get another public key update that voids the previous one.  If there is  no node resource then we probably do not want to attempt to update.

Thinking about it, we may want to disable wireguard if there is no node resource configured for the node.

2020-04-16 16:34 UTC, realgaurav commented on daemon/daemon.go
> +			fc.handleWireguardStatusUpdate(ctx, msg)
@robbrockbank the latest update addresses the comment here. PTAL

2020-04-16 17:55 UTC, robbrockbank commented on daemon/daemon.go
> +			go fc.writeWireguardStatus(ctx, msg.PublicKey)
This can create multiple go routines because the status doesn't get updated until he writeWireguardStatus has executed to a certain point..

I find this count and lock logic quite confusing - it seems unnecessarily complicated and not very go-ish. It's also quite error prone especially when triggering multiple go routines everywhere.  It would be more common to have a single constantly running "write" loop that loops forever pulling data off a channel.  That's what we do for the StatusUpdatesFromDataplane.

There are multiple ways you can handle error cases (i.e. not being able to reconcile or write the data).  One would be to use a channel with size 1:
-  The data plane message always writes into the channel, blocking if the channel is full
-  The write/reconcile processing puts the entry back into the channel if it fails to reconcile or write.  If the channel is full then no-op - a full channel would mean a new data plane update as been received and that should take precedence.
-  Generally I'd expect some kind of back off when the reconciliation fails because we don't want to tight loop attempting to write.  You can also use timers as a channel to simplify the logic for this.

Something like this moves all the logic effectively into a single loop with a single "reconcile function" that would compare and update values as necessary.
```
fc.WireguardStatusUpdatesFromDataplane = make(channel *proto.WireguardStatusUpdate, 1)

-------

case *proto.WireguardStatusUpdate:
   fc.WireguardStatusUpdatesFromDataplane <- msg

------

var current *proto.WireguardStatusUpdate
var timer time.Timer
for {
  if current != nil {
    err := reconcile(current)
    if err == nil {
      current = nil
    } else {
      // Start timer
    }
  }

  if current == nil {
    // Block until we get an update
    current <- fc.WireguardStatusUpdatesFromDataplane
  } else {
    // Block until we either get an update or it's time to retry a failed update.
    select {
      case current <- fc.WireguardStatusUpdatesFromDataplane:
      case <- timer:
    }
    // cancel timer
  }
}

2020-04-16 18:08 UTC, robbrockbank commented on daemon/daemon.go
> +	kv, err := fc.datastore.Get(getCtx, model.WireguardKey{NodeName: fc.config.FelixHostname}, "")
You are trying to read/write to the v1 datastore.  We don't support that.

You need to read and write the the v3 node resource.

If the node resource does not exist then don't attempt to write to it.  It should already exist in Felix when it starts up (at least in k8s).  In OpenStack it won't exist and we shouldn't try to write to it.

This means attempting to set a public key when the node resource does not exist is an error condition.  This also means we should not attempt to enable wireguard if the node resource does not exist.

2020-04-16 18:32 UTC, robbrockbank commented on daemon/daemon.go
> +			go fc.writeWireguardStatus(ctx, msg.PublicKey)
FTR, if you wanted to stick with the approach of triggering an update, but to squash multiple pending triggers into a single trigger (which is how I interpret your count/lock logic), then you can also do that fairly naturally with channels too.  You can create a single "update" channel which has length 1.  When you write a value into this channel (to trigger it), you can simply no-op if you cannot write into the channel (by adding a default branch) - this ensures you write to an empty channel and don't write if the channel already has something in it.

2020-04-16 18:34 UTC, robbrockbank requested changes
This logic is incorrect.  The locking/counting logic does not quite work correctly.  Also, you are reading and writing to the wrong resource.

See comments inline.

2020-04-16 18:56 UTC, realgaurav commented on daemon/daemon.go
> +			go fc.writeWireguardStatus(ctx, msg.PublicKey)
I was afraid about the non-go-ish changes. But I am not sure about the multiple go-routine part though, given I am proposing to `return` after spinning a go-routine. About the _tight_ for loop, I was hoping that the idea that we are waiting for a running go-routine to quit will be a sufficient justification. In case of first time execution, `for` loop should be more conditional than busy loop.

I wanted to test the idea so I wrote a small test code to verify the logic. When testing the following change, I could see only 1 go-routine in action at a time. This is true in both the cases where an earlier go-routine (similar to write logic in Felix) is already in progress or has successfully finished.

```
package main

import (
    "fmt"
    "time"
    "sync"
)

func inner(i int, quit chan bool, num *int, mut *sync.RWMutex) {
    defer func() {
        mut.Lock()
        *num--
        mut.Unlock()
    }()

    mut.Lock()
    *num++
    mut.Unlock()

    j:=0
    for {
        select {
        case <-quit:
            fmt.Printf("aborted inner(%d)\n", i)
            return
        default:
            if (j == 6) {
                return //comment, un-comment to 
            }
            time.Sleep(500 * time.Millisecond)
            fmt.Printf("%d: %d\n", i, j)
        }
        j++
    }
}

func main() {
    quit := make(chan bool, 1)
    var mut sync.RWMutex
    var num int

    go inner(1, quit, &num, &mut)
    time.Sleep(5 * time.Second)

    mut.RLock()
    n := num
    mut.RUnlock()
    if n == 1 {
        quit <- true
    }

    for {
        mut.RLock()
        n := num
        mut.RUnlock()

        if n == 0 {
            go inner(2, quit, &num, &mut)
            break
        }
    }
    time.Sleep(5 * time.Second)
}
```

I did consider channels but couldn't wrap my head around the logic to avoid blocking on read from wireguard-write-logic in the main readMessagesFromDataplane() go-routine.

For my understanding and future references, I would love to know why the suggested logic is incorrect, when you have a chance of course :) Meanwhile, I will take a look at the suggested changes.

2020-04-16 21:10 UTC, robbrockbank commented on daemon/daemon.go
> +			_, err := fc.datastore.Apply(applyCtx, &kv)
Note that a Zero public key should remove the key (empty string) or no-op if the node does not exist

2020-04-18 03:15 UTC, robbrockbank commented on daemon/daemon.go
> +			log.Panicf("Failed to read v3 node resource: %v", err)
No - we shouldn't panic because we can't read the node resource when we get an update.

I don't understand why you are doing some of the datastore access here and some in writeWireguardStatusToNode.  You should always be reading the node resource before attempting to write back into it - otherwise you can't use the resource version to handle atomicity.

2020-04-18 03:16 UTC, robbrockbank commented on daemon/daemon.go
> +			log.Panicf("Failed to read v3 node resource: %v", err)
Keep it simple - implement a single method that gets/correlates and if necessary updates the node status.

2020-04-18 03:17 UTC, robbrockbank commented on daemon/daemon.go
> +			fc.handleWireguardStatusUpdate(ctx, msg)
I think it's generally best for the raiser to mark as resolved, otherwise it's easy for the reviewer to skip over and check previous comments are addressed, which I don't think they are.

2020-04-18 03:19 UTC, robbrockbank commented on daemon/daemon.go
> +			fc.handleWireguardStatusUpdate(ctx, msg)
Not sure why you don't follow the same methodology as the fc.StatusUpdatesFromDataplane and simply push the message into the channel here rather than calling into a function.  You'll have another go routine that then pulls of this channel and does all the processing it needs to do.  I don't think calling out to a function here buys you a whole lot especially because the split of responsibility is not correct.

2020-04-18 03:19 UTC, robbrockbank commented on daemon/daemon.go
> +			log.Panicf("Failed to read v3 node resource: %v", err)
I think the code sketch I provided is a better and clearer implementation.

2020-04-18 03:20 UTC, robbrockbank commented on daemon/daemon.go
> +	node := &apiv3.Node{
Nope.  You should get the current node settings before updating the resource and then updating it.

2020-04-18 03:22 UTC, robbrockbank commented on daemon/daemon.go
> +		case <-ticker.C:
This will seg fault I think.  Ticker is only initialized under error condition.

I think the code sketch I provided already accounted for this.

2020-04-18 03:32 UTC, robbrockbank commented on daemon/daemon.go
> +	// Disabled Wireguard configuration if the public-key sent from dataplane is empty.
This isn't what we discussed.  I said that wireguard should be disabled on start-up if the node resource does not exist - the reason being is that there is no node resource to update.  This is therefore the wrong place to do that particular check - it needs to be made in the daemon processing, probably after loading the config - if there is no node resource for this host then make sure wireguard is disabled.

Another reason there is no point in changing this configuration here is that it won't do anything.  The config loaded at start up is passed to the data plane component at start up - once started changing these config values will have no impact.

2020-04-20 20:24 UTC, realgaurav reviewed
After going through last review comments, I have updated the PR to address the following:

1. Use single go-routine to directly handle wireguard status update messages.
2. Use reconciler doing `get`/`update` in a sequence.
3. Use status message handler added in earlier review comment.
4. Add node-resource check in `daemon.Run()` after configuration load.

In addition to above and FWIR from our last conversation --
1. I have used `jitter` to keep randomized retries between 2-4 seconds instead of `Timer`.
2. I am checking error types returned from `get`/`update` to decide between recoverable/unrecoverable errors and ignoring status update logging an error in case of unrecoverable error.

Let me know if I missed anything or any of the above suggested 2 points are not correct.

2020-04-20 21:17 UTC, robbrockbank requested changes
See inline.

2020-04-20 21:17 UTC, robbrockbank commented on daemon/daemon.go
> +		// create a v3 client for managing node resource.
Not sure you need to create another client.  Also, it would be nice to have the load config from datastore all being in one place.

Just reading through the code above I can see that we call out to `loadConfigFromDatastore` which loads initial config from the global and per-node FelixConfiguration resources _and_ the local Node resource.  So it feels like that would be the right place for this processing.  You can access the Node resource using the backend client. This seems a little more fiddly except for the fact that there is already explicit processing to handle the node not existing.

I would suggest:
-  Update getAndMergeConfig() to take another parameter of type map[string]string, say "doesNotExistValues"
-  If the resource does not exist, update the config values with the values from the "doesNotExistValues" map.

To handle the node updates you should probably use the v3 client rather than the backend client. I don't think you should be creating another client for that though.  Rather than creating the backend client above, create the v3 client, and then obtain the backend client from that.

the v3 client implements a method called Backend(), so all you have to do is cast the v3 client onto an interface that contains the Backend() method to invoke it.

2020-04-20 21:17 UTC, robbrockbank commented on daemon/daemon.go
> +		if err != nil {
You need to be more careful with the error handling here.  In this case we are only interested in an error that indicates the resource does not exist, but you are lumping all errors into the same bucket.  I think if you build this into `getAndMergeConfig` as I suggest above then this case is already handled.

2020-04-20 21:26 UTC, robbrockbank commented on daemon/daemon.go
> +			log.Panic("v3 node resource must exist for Wireguard.")
ResourceDoesNotExist means there is no node resource rather than the node was empty.

Based on our conversation last week, this scenario might be the case for openStack and is therefore a valid scenario.  I think the logic should be:
-  If public key is "zero" then it's ok for the node not to exist - because no node and no public key can be considered the same thing.
-  If public key is "non-zero" then panic i think is ok - it would force a restart that would then disable wireguard.

2020-04-20 21:33 UTC, robbrockbank commented on daemon/daemon.go
> +			case cerrors.ErrorValidation:
Is you intention here that these three cases are handled the same?  If so then the code is not correct.  You need to include fallthrough statements.

If your intention is that ErrorValidation and ErrorResourceUpdateConflict are no-ops then you don't really need to include them here.

---

That said, I think *all* errors should be retryable.  Even an unauthorized could become authorized when RBAC config is applied.  You could argue that ErrorValidation is a bug and we should probably panic.  Personally though, the only error I think is worth explicitly handling is ErrorResourceUpdateConflict.  This error indicate that someone was making a change the same time as you and they beat you to it, so you are attempting to update an out-of-date resource.

With ResourceUpdateConflict I think you can probably retry straight away.  So perhaps loop here three times attempting to read and update the resource.  If the error is update conflict continue the loop to retry, otherwise break.  If failed to update, return the last error.

2020-04-20 21:42 UTC, realgaurav commented on daemon/daemon.go
> +			log.Panic("v3 node resource must exist for Wireguard.")
> If public key is "zero" then it's ok for the node not to exist - because no node and no public key can be considered the same thing.

If wireguard in disabled daemon.Run() will there still be an update from Dataplane setting publicKey to ""?

2020-04-21 01:04 UTC, realgaurav commented on daemon/daemon.go
> +			log.Panic("v3 node resource must exist for Wireguard.")
Assumed answer is no and handled  for _public key is "zero"_

2020-04-21 05:14 UTC, robbrockbank commented on daemon/daemon.go
> +	defer cancel()
Not sure need to defer the cancel do we, and it's generally better not to use defer within a loop.

2020-04-21 05:14 UTC, robbrockbank commented on daemon/daemon.go
> +				if retries < 3 {
nit:

```
var retries int
loop:
case cerrors.ErrorResourceUpdateConflict:
	if retries < 3 {
		log.Debug("Update conflict, retrying update")
		retries++
		goto loop
}
```

urm, why not just use a for loop here:

```
for iteration := 0; iteration < 3; iteration++ {
	case cerrors.ErrorResourceUpdateConflict:
		continue
	...
	break;
}
```

2020-04-21 05:20 UTC, robbrockbank commented on daemon/daemon.go
> +				// Current updated from the
incomplete comment

2020-04-21 05:24 UTC, robbrockbank commented on daemon/daemon.go
> +		defer cancel()
sim. here with this defer.

2020-04-21 06:30 UTC, robbrockbank approved these changes
lgtm

2020-04-21 06:31 UTC, merged